rm /usr/local/lib/libmuzi_base.a
rm /usr/local/include/process_info.h
rm /usr/local/include/thread.h
rm -r /usr/local/include/test
rm /usr/local/include/config.h
rm /usr/local/include/traced_exception.h
rm /usr/local/include/string_proxy.h
rm /usr/local/include/macros.h
rm /usr/local/include/fixed_buffer.h
rm /usr/local/include/noncopyable.h
rm /usr/local/include/stacktrace.h
rm /usr/local/include/timezone.h
rm /usr/local/include/outputer.h
rm /usr/local/include/file_utils.h
rm /usr/local/include/condition.h
rm /usr/local/include/weak_callback.h
rm /usr/local/include/mutex.h
rm /usr/local/include/countdown_latch.h
rm /usr/local/include/async_outputer.h
rm /usr/local/include/log_file.h
rm /usr/local/include/timestamp.h
rm /usr/local/include/singleton.h
rm /usr/local/include/log_stream.h
rm /usr/local/include/current_thread.h
rm /usr/local/include/thread_pool.h
rm /usr/local/include/logger.h
rm /usr/local/lib/libmuzi_net.a
rm /usr/local/include/event_loop_thread_pool.h
rm /usr/local/include/event_loop_thread.h
rm /usr/local/include/timer.h
rm /usr/local/include/timer_queue.h
rm /usr/local/include/tcp_server.h
rm /usr/local/include/socket.h
rm /usr/local/include/address.h
rm /usr/local/include/inet_address.h
rm /usr/local/include/buffer.h
rm /usr/local/include/poller.h
rm /usr/local/include/endian_transform.h
rm /usr/local/include/tcp_connection.h
rm /usr/local/include/socket_ops.h
rm /usr/local/include/connector.h
rm /usr/local/include/channel.h
rm /usr/local/include/local_address.h
rm /usr/local/include/tcp_client.h
rm /usr/local/include/event_loop.h
rm -r /usr/local/include/poller
rm /usr/local/include/poller/epoll_poller.h
rm /usr/local/include/acceptor.h
rm -r /usr/local/test
